### ISSUE TITLE
Can't see all redirects (filtered results stuck)

### ISSUE THREAD

**Issue by texasbaptists** [nystudio107/craft-retour#196] opened 2021-07-28 13:31 UTC
### Describe the bug
On example.com/admin-area/retour/redirects I only see results of my previous "Search for" but the search filter ui element isn't showing up, so I can't click the "Reset" Button that is typically there and see all my Redirects. 

If I go to Developer tools I can delete the Local Storage in the Application with the `retour-redirects-state-sitehandle` key and I can see it again. This has happened twice, it is not consistently getting stuck. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to "/admin/retour/redirects/"
2. Use 'Search for:' 
3. Go to another page
4. Go back to "/admin/retour/redirects/" ... sometimes I see the "Search for" ui element and sometimes I don't. 

### Expected behaviour
To see the "Search for" element so I can click the "Reset" button.

### Screenshots
what is expected (when it is working correctly):
<img width="400" alt="Screen Shot 2021-07-28 at 8 24 02 AM" src="https://user-images.githubusercontent.com/28350515/127330028-8fef804a-98d9-4290-aca4-53872be13a53.png">

what i see (when it's not working correctly)
<img width="366" alt="Screen Shot 2021-07-28 at 8 24 23 AM" src="https://user-images.githubusercontent.com/28350515/127330153-e8939c19-2446-45c7-b42f-27a572e93181.png">

### Versions
- Plugin version: 3.1.57
- Craft version: 3.7.6

**Comment by khalwat** [comment] 2021-07-28 15:35
I'm unable to reproduce this locally. Can you give me a methodology that allows it to be reproduced?

**Comment by texasbaptists** [comment] 2021-07-28 17:52
Ok. I have figured out when it happens consistently for me. 

1. Create a redirect for `/test`
2. Search redirects for `test`.  
3. Click the checkbox next to `/test` to select it. (this is when the filter ui disappears and is replaced with the UI for the selected elements)
4. Go to the settings icon dropdown menu and click `Delete`

Result = The dropdown menu with the settings icon is still there instead on the filter UI, but nothing is selected. If there are still filter results, you can select all and deselect which makes the filter UI return, but if you don't have any results you can't deselect anything and are stuck until you delete the Local Storage setting.

**Comment by texasbaptists** [comment] 2021-07-28 18:03
Another thing that makes this happen and is easier to reproduce. 

1. On the redirects page, select any redirects. 
2. Hit browser refresh.

**Comment by chadwells** [comment] 2021-08-04 15:50
This also just happened to me. Exact same scenario. Freaked me out a bit as I thought I lost all my stored redirects!

**Comment by khalwat** [comment] 2021-08-04 16:10
Fixed in: https://github.com/nystudio107/craft-retour/commit/33b613f0c6efa375b007248dd0124ed422d45f31

**Comment by khalwat** [comment] 2021-08-04 16:15
Released as 3.1.58: https://github.com/nystudio107/craft-retour/releases/tag/3.1.58

**Closed as completed by khalwat** 2021-08-04 16:15 UTC
Labels: bug

**Comment by texasbaptists** [comment] 2021-08-09 13:30
Thanks! Appreciate the fix.
