### ISSUE TITLE
Can't access plugin dashboard templates

### ISSUE THREAD

**Issue by leogenot** [nystudio107/craft-retour#302] opened 2024-05-13 12:34 UTC
### Describe the bug
On fresh install of craft cms 3.9.13, installing the plugin through plugin store or command line 
(`composer require nystudio107/craft-retour` and then `./craft install/plugin retour`)
the plugin dashboard isn't accessible:
<img width="1302" alt="Screenshot 2024-05-13 at 14 31 42" src="https://github.com/nystudio107/craft-retour/assets/45610291/8666e991-045d-48d1-8dd7-419bd6805230">

### To reproduce
Steps to reproduce the behaviour:
1. Fresh install of craft cms 3: `composer create-project "craftcms/craft:^3"`
2. Go to plugin store, install Retour
3. Can't access Retour dashboard

### Expected behaviour
The dashboard should be accessible

### Versions
- Plugin version: 3.2.14
- Craft version: 3.9.13

**Comment by khalwat** [comment] 2024-05-13 22:39
That error doesn't seem to be coming from Retour? Can you provide a screenshot with the full context in terms of the URL you're attempting to navigate to?

**Comment by leogenot** [comment] 2024-05-14 06:38
Hey, I am trying those URLS:

`/admin/retour/dashboard`
`/admin/retour/settings`
`/admin/retour/redirects`
`/admin/retour/shortlinks`

which none of the above work....

<img width="774" alt="Screenshot 2024-05-14 at 08 37 37" src="https://github.com/nystudio107/craft-retour/assets/45610291/521445f0-dd78-43ed-8bbe-0dd1ce4ff23b">

And in case this can help:

<img width="716" alt="Screenshot 2024-05-14 at 08 38 59" src="https://github.com/nystudio107/craft-retour/assets/45610291/812b61f4-b881-4334-8099-2deb12df7d02">

**Comment by khalwat** [comment] 2024-05-20 19:16
I tried replicating the issue with:

Craft CMS 3.9.13
Retour 3.2.14

...and I'm unable to replicate it.

Could this possibly be some kind of localization issue, where a title isn't available in another language or such?

**Comment by khalwat** [comment] 2024-05-23 18:59
At this point I'm wondering if there's some kind of regression in Craft causing this issue

**Comment by khalwat** [comment] 2024-05-23 19:04
Same as: https://github.com/nystudio107/craft-retour/issues/304

**Comment by leogenot** [comment] 2024-05-27 07:46
Hey again, it's weird cause uninstalling the plugin from old craft 3 websites where it works fine then breaks it the same way when re-installing it afterwards...

**Comment by khalwat** [comment] 2024-05-28 18:58
I'd be happy to jump on a video conference where we can look into this issue if you are able to reproduce it in your local development environment:

https://savvycal.com/nystudio107/chat

I'm unable to reproduce the issue, and I've done code review without seeing anything that I can tell would be going wrong on the Retour end of things here.

**Comment by leogenot** [comment] 2024-05-28 19:03
Perfect, I scheduled on your link 👌

**Comment by khalwat** [comment] 2024-05-30 13:47
Fixed in 3.2.15 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.15

**Closed as completed by khalwat** 2024-05-30 13:47 UTC
Labels: bug

**Comment by leogenot** [comment] 2024-06-03 06:44
Working perfectly thanks again!
