### ISSUE TITLE
Automatic Redirects Don't Work on Multiple Sites

### ISSUE THREAD

**Issue by kmgdevelopment** [nystudio107/craft-retour#41] opened 2019-02-15 18:43 UTC
When the "Create Entry Redirects" setting is enabled, redirects are only created when an entry on the parent site is changed. If an entry slug is changed on a secondary site, no redirect is created.

Steps to Reproduce:

1. Set up more than one site
2. Enable "Create Entry Redirects" in Retour
3. Switch to a non-primary site
4. Update an entry's slug

Craft 3.1.9.1
Retour 3.1.6

**Comment by khalwat** [comment] 2019-02-16 03:22
hrm interesting. I will have a look, thanks!

**Comment by khalwat** [comment] 2019-02-19 16:31
@kgrote to help me track this down, would you be able to do this in local dev with `devMode` on:

- Delete your logs in `storage/logs/`
- Reproduce the issue by changing a slug on a non-primary site
- Attach your web.log here?

Retour is in theory handling multi-site already, and it logs quite a few things that will help me track this down if `devMode` is on.

**Comment by kmgdevelopment** [comment] 2019-02-19 20:05
Hi Andrew,

Is there an email I can send my log to? I'd rather not post it publicly.

**Comment by khalwat** [comment] 2019-02-19 21:34
Sure! andrew@nystudio107.com

**Comment by khalwat** [comment] 2019-02-20 14:13
Received the file, thanks! Also what would help me replicate the issue (and thus be able to fix it) would be any details on your multi-site setup. Is it fairly standard in that you just have more than one site, and all entries propagate across to each site? Or are they all localized per-site?

**Comment by kmgdevelopment** [comment] 2019-02-20 17:52
Each site has their own per-site entries. So the section "Resources" is available to all sites, but the entries do not propagate to each other.

**Comment by kmgdevelopment** [comment] 2019-02-21 21:03
Hey Andrew,

So it looks like redirects on multiple sites aren't working at all. I just tried to manually add a redirect for one of my subdomains but it doesn't work when you hit the URL. However it DOES redirect if you hit the URL on the default site.

**Comment by khalwat** [comment] 2019-02-21 21:05
Was this redirect set up as being assigned specifically to the subdomain in question?

I think we should probably do a screen sharing when it's convenient for you, so I can understand the setup you're using.

**Comment by kmgdevelopment** [comment] 2019-02-21 21:08
Yes, it's assigned to the specific subdomain, and it shows up when I filter by subdomain.

I'm available for a screenshare anytime today. Shoot me an email whenever you like.

**Comment by khalwat** [comment] 2019-02-21 21:09
So I can do it now if you're able, but a caveat is that I'm not in the office, I'm at home with two sick kids -- if that's okay with you, hit me up on the Craft Discord (handle: **andrew.welch#0107** ) to coordinate?

**Comment by khalwat** [comment] 2019-02-23 04:06
In case anyone else is reading this later, the second separate issue in this thread "it looks like redirects on multiple sites aren't working at all" ends up not being an issue at all.

Retour does nothing until a 404 is thrown, and in this case, the entry existed, so a 404 wasn't thrown, so the redirect didn't happen.

**Comment by kmgdevelopment** [comment] 2019-03-12 22:25
How's this coming along?

**Comment by khalwat** [comment] 2019-03-14 01:51
I'm hoping to have something shortly (tomorrow most likely).

**Comment by khalwat** [comment] 2019-03-20 15:22
This didn't make it into the 3.1.7 release, but it'll be addressed shortly thereafter

**Comment by khalwat** [comment] 2019-04-02 14:31
Fixed in https://github.com/nystudio107/craft-retour/commit/dc814a83ad4d1f4f6a639258790242a392a91e95

**Closed as completed by khalwat** 2019-04-02 14:31 UTC
Labels: bug
