### ISSUE TITLE
Fully Qualified URL as destination being prepended with current host

### ISSUE THREAD

**Issue by mattbloomfield** [nystudio107/craft-retour#316] opened 2024-12-02 17:57 UTC
### To reproduce
Steps to reproduce the behaviour:
1. Go to Redirects
2. Create a static redirect
3. Enter a Legacy URL Pattern. e.g. /on-demand/us-chamber-foundation/partnering-for-prosperity-womens-global-leadership
4. Choose Path Only
5. Set a destination URL: e.g. https://www.uschamberfoundation.org/corporate-social-responsibility/partnering-for-prosperity-empowering-women-globally-with-the-gwim-program
6. Choose Exact Match & 301 permanent

### Expected behaviour
The redirect would take you to the fully qualified URL

### Result
It takes you to https://www.uschamber.com/https://www.uschamberfoundation.org/corporate-social-responsibility/partnering-for-prosperity-empowering-women-globally-with-the-gwim-program

where `https://www.uschamber.com` is my current host

### Screenshots
<img width="924" alt="image" src="https://github.com/user-attachments/assets/8e6bb87f-d395-4b39-bf75-b1606ef6ccfc">

### Versions
- Plugin version: dev-develop-v4 --- sorry 😃 
- Craft version: Craft Pro 4.12.3
--

<br class="Apple-interchange-newline">

**Comment by khalwat** [comment] 2024-12-02 18:31
Can you reproduce this using the current release version of Retour, or only with the `dev-develop-v4` version?

**Comment by mattbloomfield** [comment] 2024-12-02 18:31
Actually, closing this, I updated to a real version (4.1.19) and everything works as expected

**Comment by khalwat** [comment] 2024-12-02 18:32
I'm going to keep it open to make sure it's addressed in the release version, since it's a regression in `dev-develop-v4`

**Comment by mattbloomfield** [comment] 2024-12-02 19:00
It was only happening on the dev-develop-v4 version.

Currently released version has no issue

Matt Bloomfield
202-631-1482

**Comment by khalwat** [comment] 2024-12-03 18:40
Fixed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2024-12-03 18:40 UTC
Labels: bug
