### ISSUE TITLE
CP pages are blank

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-retour#229] opened 2022-04-14 16:47 UTC
### Describe the bug
When I attempt to load a Retour route — e.g., `/admin/retour/redirects` — the page loads but the content pane is blank. Even after clearing caches in Utilities and in my browser, the page remains blank.

I am seeing five console errors on Retour routes only:

```
Failed to find a valid digest in the 'integrity' attribute for resource ...
```

It lists:
- vueComponentNormalizer
- purify
- vue-apexcharts
- retour
- dashboard

### Screenshots
<img width="1124" alt="retour" src="https://user-images.githubusercontent.com/5922913/163435788-df1d96f8-d154-4aa1-b79e-d043bb369911.png">

### Versions
- Plugin version: 3.1.71
- Craft version: 3.7.38

**Comment by chrismlusk** [comment] 2022-04-14 17:03
Looks like this is happening in Chrome and Safari. When I try Firefox, everything loads correctly.

**Comment by khalwat** [comment] 2022-04-14 20:13
I'm unable to reproduce this issue -- do you have a Content Security Policy (CSP) on your site, perhaps?

**Comment by chrismlusk** [comment] 2022-04-15 18:13
The CSP response header I see is 

```
content-security-policy: frame-ancestors 'self'
```

**Comment by khalwat** [comment] 2022-04-15 18:15
Is this something you're adding manually? Does anyone else see this issue, or just you?

**Comment by tomgooden** [comment] 2022-04-15 20:28
We're seeing the same (or similar) issue: /redirects and /dashboard have recently gone blank (see "No Data Available")

<img width="1489" alt="CleanShot 2022-04-15 at 13 27 23@2x" src="https://user-images.githubusercontent.com/150880/163628990-5839a7e5-045f-42b0-b4a6-aff52fc887d4.png">

Craft CMS 3.7.34
Retour 3.1.70

**Comment by khalwat** [comment] 2022-04-15 20:31
@tomgooden That's a different issue entirely, I think -- what is in your JavaScript console?

**Comment by tomgooden** [comment] 2022-04-15 20:56
Ah, right. We see a mixed content error w/an insecure XMLHttpRequest endpoint

**Comment by khalwat** [comment] 2022-04-15 21:02
Sounds like you might have an issue with your `siteUrl` @tomgooden

**Comment by khalwat** [comment] 2022-04-19 13:40
@chrismlusk any word?

**Comment by chrismlusk** [comment] 2022-04-19 19:39
No, I don't think I'm adding the CSP manually. I have confirmed that other people are seeing the blank screens too.

**Comment by khalwat** [comment] 2022-04-19 20:42
Is this happening in your local dev environment as well as on production/staging?

**Comment by chrismlusk** [comment] 2022-04-20 00:20
This does not happen in my local dev environment, but I was able to reproduce in staging — with a catch.

I was actually able to load Retour admin pages just fine, but after doing a hard refresh (`Command + Shift + R`) I now see a blank page and have the same console errors.

**Comment by khalwat** [comment] 2022-04-20 00:25
If it's not happening on your local dev environment, then it's very likely something environmental on your staging/production server.

How can we diagnose how you have that set up?

**Comment by chrismlusk** [comment] 2022-04-20 00:34
Gotcha. I'm not well versed on that side of things, but this site is hosted with Servd and connected to Cloudflare. What information can I find out to help you out?

**Comment by khalwat** [comment] 2022-04-20 00:35
Ah great. I will ping Matt to see if he has any input on this.

**Comment by mattgrayisok** [comment] 2022-04-20 11:06
Hey!

If we think the problem is being caused by the CSP header then that's being added by Craft here:

https://github.com/craftcms/cms/blob/6d9bcd3bed7e84c4d17b836825f57b970367b7b8/src/web/Application.php#L186

I'm not an expert in this stuff but I'd check a couple of things:

- Whether the script files are being loaded using the exact same domain as that used to access the Craft CP
- Whether the script tags in the HTML have an `integrity` attribute and whether that has any content.

**Comment by khalwat** [comment] 2022-04-20 15:14
@mattgrayisok yeah the thing is tho... why is no one else seemingly having this issue? I can't reproduce it either in local dev, or on any other product/staging sites I have access to (including some on servd.host). It's perplexing.

**Comment by mattgrayisok** [comment] 2022-04-21 17:17
Agreed, there must be something different with this project specifically. @chrismlusk if it's still an issue would you mind checking the HTML of the pages to see if the scripts are being pulled in cross-domain or have an `integrity` prop in the script tags?

**Comment by chrismlusk** [comment] 2022-04-21 17:25
Sure thing. Here's an edited view of what I see from one of the broken scripts:

```html
<link
    href="https://osh-stage.onedesigncompany.dev/../vueComponentNormalizer.9fe6193d.js"
    rel="modulepreload"
    crossorigin
    integrity="..."
>
```

**Comment by KatieMFritz** [comment] 2022-06-20 21:44
I'm having the same problem as @chrismlusk on a staging site after upgrading to Craft 4.0.4 and Retour 4.0.1:
- Multiple `Failed to find a valid digest in the 'integrity' attribute for resource...` errors
- Works on Firefox but not Chrome
- Retour dashboard on CP is missing all data
- Works locally

We use Cloudflare to restrict access to our staging site. We are also getting a 404 for the home page URL on staging only. (that's on Firefox as well).

**Comment by khalwat** [comment] 2022-06-23 01:02
I think you might have a setting in CloudFlare that is interfering with the scripts. I'm aware of an Auto Minify that dynamically minifies the JavaScript, which changes it's hashed value, which would then cause it to fail the SRI integrity check built into it.

I could disable the SRI generation for the scripts in the CP, but that would make me a little sad because it's giving up a security feature.

Probably this has to do with your CloudFlare configuration; I'd suggest disabling things for the CP that mess with loaded resources @KatieMFritz

**Comment by khalwat** [comment] 2022-06-23 01:03
I guess I can disable SRI if this is going to cause support headaches with misconfigured CloudFlare, or other setups though.

**Comment by khalwat** [comment] 2022-06-23 02:39
Addressed in: <https://github.com/nystudio107/craft-retour/commit/0c46d3b8fdfbfd7c4db554c7bde180143324ac0e> & <https://github.com/nystudio107/craft-retour/commit/3861995bd65681bbd983630d915d25bba3ccdb51>

Released as:

`3.1.73` - https://github.com/nystudio107/craft-retour/releases/tag/3.1.73

`4.0.2` - https://github.com/nystudio107/craft-retour/releases/tag/4.0.2

**Closed as completed by khalwat** 2022-06-23 02:39 UTC
Labels: bug
