### ISSUE TITLE
Ability to schedule redirects to be published and removed

### ISSUE THREAD

**Issue by aaronbushnell** [nystudio107/craft-retour#140] opened 2020-10-13 20:13 UTC
### Is your feature request related to a problem? Please describe.
On some occasions we've had clients who want to start and stop redirects based on particular dates. It would be fantastic if Retour allowed us to set publish and expiration dates on these types of redirects.

### Describe the solution you would like
The addition of publish and expiration dates on each redirect entry.

### Describe alternatives you have considered
I think the only alternative I've found is to simply manually add/remove them or author some kind of import/deletion process that interfaces with Retour

### Additional context
N/A

**Comment by khalwat** [comment] 2020-12-11 03:30
What's the use-case here @aaronbushnell -- ie, what are they trying to do?

**Comment by aaronbushnell** [comment] 2020-12-13 16:21
We pretty frequently need to launch pages for clients that are legally required to only go live at midnight day-of.

It would be awesome if we could setup redirects for launches like these beforehand and schedule them to be “enabled” on a specific day and time and “disable” them later like we can with the Craft entries for this same work. 

Does that make sense?

**Comment by thisisjamessmith** [comment] 2022-07-26 10:35
Also had a client request for this functionality, +1

**Comment by khalwat** [comment] 2022-07-26 13:15
It'd need some kind of external trigger such as a cron job or the like -- the same way that's needed for future-published entries in Craft.

**Comment by thisisjamessmith** [comment] 2022-07-26 17:13
I'm fairly sure Craft doesn't need an external trigger for future publish dates - it "just works" for me? I presume an entry's status is reset during the request if the publish date has passed. (Though static page caching complicates matters). But yep, if a cron job is necessary I think that's a fine approach.

**Comment by khalwat** [comment] 2022-07-26 17:51
I'm not aware of it "just working" with Craft... I'd be interested in exactly how they are doing that. Maybe it does work if you're not implementing a caching strategy?

**Comment by thisisjamessmith** [comment] 2022-07-26 18:00
Yep I tested now and it does work automatically. (For cache evasion I dynamically reload the relevant content chunk via ajax. It’s typically just time sensitive listing pages like events that need it, and most of the time the user will never notice the sleight of hand!)

**Comment by khalwat** [comment] 2022-07-26 18:02
So I think I didn't communicate this well.  I know the entries will start responding to queries and such, but I did not think that things like Craft's template caches would automatically invalidate?

In any event, I typically use a static cache, so I'd need a system for handling that cache busting.

**Comment by khalwat** [comment] 2022-08-28 22:44
@aaronbushnell 
> We pretty frequently need to launch pages for clients that are legally required to only go live at midnight day-of.

> It would be awesome if we could setup redirects for launches like these beforehand and schedule them to be “enabled” on a specific day and time and “disable” them later like we can with the Craft entries for this same work.

> Does that make sense?

So the part that still doesn't make sense to me is... why are redirects involved at all here? Why not just have the entries go live at midnight?

**Comment by aaronbushnell** [comment] 2022-08-28 23:10
We often use Retour for “vanity URLs” that redirect users to other entries. So maybe the entry URL is /foo/bar/save-the-date but the redirects we create are for things like /the-big-day and /celebrate. 

Does that help? That’s the thing we often like to schedule _with_ the launch of the entry.

**Comment by khalwat** [comment] 2022-08-28 23:56
Re: Vanity URLs, you might like the new "Short Links" feature I've added:

<img width="788" alt="Screen_Shot_2022-08-25_at_2 47 45_PM" src="https://user-images.githubusercontent.com/7570798/187100066-e87ec7a7-ca73-4380-a41d-98a8d1e24906.png">
<img width="788" alt="Screen_Shot_2022-08-25_at_2 47 31_PM" src="https://user-images.githubusercontent.com/7570798/187100067-d2a886ec-c66f-4916-a89d-6c17c71c209e.png">

It's nothing you couldn't do with Retour already, as you've noted, but because it's done via a Field, it's something content authors can easily work with.

Also the way it works I think gives you exactly what you want. The vanity URL / short link is enabled / disabled with the status of the element. So your vanity URL / short link won't go live until your entry goes live by being enabled.

**Comment by khalwat** [comment] 2022-08-28 23:57
> We often use Retour for “vanity URLs” that redirect users to other entries. So maybe the entry URL is /foo/bar/save-the-date but the redirects we create are for things like /the-big-day and /celebrate.
> 
> Does that help? That’s the thing we often like to schedule with the launch of the entry.

I guess I still don't get it. If you create the vanity URL / short link ahead of time, I don't understand the benefit of it not being live yet. You could have it there, redirecting to the entry URL, which will just 404 until you've published it.

And a 404 is what you'd get for the vanity URL / short link if it didn't exist yet anyway.

**Comment by khalwat** [comment] 2022-08-30 17:41
I'm going to close this issue, because I think the problem is neatly solved by the Short Link field:

https://nystudio107.com/docs/retour/shortlinks.html

The enabled/disabled state of the Short Link redirect mirrors the enabled/disabled status of the element.

Craft CMS 3: https://github.com/nystudio107/craft-retour/releases/tag/3.2.0

Craft CMS 4: https://github.com/nystudio107/craft-retour/releases/tag/4.1.0

**Closed as completed by khalwat** 2022-08-30 17:41 UTC
Labels: enhancement
