### ISSUE TITLE
Extra language parameter added

### ISSUE THREAD

**Issue by bartdebock** [nystudio107/craft-retour#294] opened 2024-02-29 13:18 UTC
### Question
We're adding redirects to a project we're developing, and are unsure if we're doing it correct. This is what we filled in: 

![image](https://github.com/nystudio107/craft-retour/assets/139547753/e3ea0217-969e-47f5-b2ab-3395200ac798)

However, in the overview and extra language parameter is added to the link, and when clicking it, that link doesn't work: 

![image](https://github.com/nystudio107/craft-retour/assets/139547753/0fb1a052-f210-40df-9acd-22264316682a)

The redirect itself does work though. 

Not sure if this is a bug or we filled in the redirect wrong.

**Comment by khalwat** [comment] 2024-03-01 03:55
Yep, this is a bug. Duplicate of: https://github.com/nystudio107/craft-retour/issues/290

**Closed as completed by khalwat** 2024-03-01 03:55 UTC
Labels: question
